#----------------------------------------------------------------#
# Vault Landing Zone
#  Creates the necessary Vault policies and roles to support Vault
#  backed dynamic credentials in TFE.
#----------------------------------------------------------------#

# Creates a Vault policy that allows tokens to read, renew, and revoke themselves, 
# as well as read from the AWS secrets engine role path. This policy will be attached
# to the tokens generated by the JWT auth method for this app.
locals {
  vault_aws_secrets_role_name = "tfe-lz-role-${var.app_name}-${var.environment}"
  aws_iam_role_arn            = "arn:aws:iam::${var.aws_account_id}:role/tfe/${var.app_name}-${var.environment}-role"
}

data "vault_policy_document" "aws_secret_auth" {
  rule {
    path         = "auth/token/lookup-self"
    capabilities = ["read"]
    description  = "Allow tokens to query themselves"
  }
  rule {
    path         = "auth/token/renew-self"
    capabilities = ["update"]
    description  = "Allow tokens to renew themselves"
  }
  rule {
    path         = "auth/token/revoke-self"
    capabilities = ["update"]
    description  = "Allow tokens to revoke themselves"
  }
  rule {
    path         = "aws/sts/${local.vault_aws_secrets_role_name}"
    description  = "Allow to generate credentials from AWS Secrets Engine"
    capabilities = ["read"]
  }
}

resource "vault_policy" "aws_secret_auth" {
  name   = local.vault_aws_secrets_role_name
  policy = data.vault_policy_document.aws_secret_auth.hcl
}

# Creates a role on an AWS Secret Backend for Vault. Roles are used to map credentials to the policies 
# that generated them.
#
# https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/aws_secret_backend_role

# NOTE THE IAM ROLE PATH PREFIX of '/tfe/'. This can be helpful to isolate these from other IAM roles in the accounts
# in AWS SCPs and other controls.
resource "vault_aws_secret_backend_role" "aws_secret_backend_role" {
  #   namespace       = var.vault_namespace
  backend         = "aws"
  name            = local.vault_aws_secrets_role_name
  credential_type = "assumed_role"
  role_arns       = [local.aws_iam_role_arn]
}

# Creates a role for the jwt auth backend and uses bound claims
# to ensure that only the specified Terraform Cloud workspace will
# be able to authenticate to Vault using this role.
#
# https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/jwt_auth_backend_role
resource "vault_jwt_auth_backend_role" "tfe_workspace_aws_reader_role" {
  backend        = var.vault_jwt_auth_path
  role_name      = "tfe-lz-jwt-role-${var.app_name}-${var.environment}"
  token_policies = [vault_policy.aws_secret_auth.name]

  bound_audiences   = [var.tfe_vault_audience]
  bound_claims_type = "glob"
  bound_claims = {
    sub = "organization:${data.tfe_organization.this.name}:project:${tfe_project.this.name}:workspace:*:run_phase:*"
  }
  user_claim = "terraform_full_workspace"
  role_type  = "jwt"
  token_ttl  = 1200
}
